### ISSUE TITLE
state_dict = checkpoint['model'] KeyError: 'model' When I using flickr30k.pth 

### ISSUE THREAD

**Issue by MARS-J** [salesforce/ALBEF#120]
I am using the Windows platform，
The command I executed was：“python Retrieval.py --config ./configs/Retrieval_flickr.yaml --output_dir output/Retrieval_flickr --checkpoint pretrain\flickr30k.pth”，
The error is：
“Traceback (most recent call last):
  File "Retrieval.py", line 376, in <module>
    main(args, config)
  File "Retrieval.py", line 257, in main
    state_dict = checkpoint['model']
KeyError: 'model'  ”
I would appreciate it very much if someone could help me solve this problem.

**Comment by T0305** [comment]
Did you solve this problem? I also encountered this problem, can you tell me how to solve it? Thank you so much

**Comment by shyammarjit** [comment]
I am also getting the same error.

**Comment by moonsbird29** [comment]
Hi, I also encountered this error, did you figure it out?
