### ISSUE TITLE
RuntimeError: invalid multinomial distribution (sum of probabilities <= 0)

### ISSUE THREAD

**Issue by cdqncn** [salesforce/ALBEF#18]
## Hi, when I runned the Retrieval.py, I met this issue. How could I repair it?

Traceback (most recent call last):
  File "Retrieval.py", line 382, in <module>
    main(args, config)
  File "Retrieval.py", line 305, in main
    train_stats = train(model, train_loader, optimizer, tokenizer, epoch, warmup_steps, device, lr_scheduler, config)  
  File "Retrieval.py", line 51, in train
    loss_ita, loss_itm = model(image, text_input,alpha=alpha, idx=idx)                  
  File "/home/ma-user/anaconda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ma-user/anaconda/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 619, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/ma-user/anaconda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ma-user/modelarts/user-job-dir/ALBEF/models/model_retrieval.py", line 130, in forward
    neg_idx = torch.multinomial(weights_t2i[b], 1).item()
RuntimeError: invalid multinomial distribution (sum of probabilities <= 0)

**Comment by LiJunnan1992** [comment]
Hi, I have updated line 120-121 of models/model_retrieval.py, which should solve this issue.

Thanks!

**Comment by zhihuacc** [comment]
> Hi, I have updated line 120-121 of models/model_retrieval.py, which should solve this issue.
> 
> Thanks!

Hi May I ask why this error happened ? because I think softmax() earlier man guarantee that the sum of probabilities = 1.

**Comment by Ngheissari** [comment]
I get the same error. None of the suggested remedies seem to work.

**Comment by guoyh0118** [comment]
怎么解决呢
