### ISSUE TITLE
Got key error when loading weights finetuning on Visual Grounding

### ISSUE THREAD

**Issue by pqviet** [salesforce/ALBEF#26]
Thank you for your sharing work. I got problems when finetuning Visual Grounding
python -m torch.distributed.launch --nproc_per_node=8 --use_env Grounding.py \
--config ./configs/Grounding.yaml \
--output_dir output/RefCOCO \
--gradcam_mode itm \
--block_num 8 \
--checkpoint ./pretrain/refcoco.pth
refcoco.pth was downloaded from your link.
Here is the error message
Traceback (most recent call last):
  File "Grounding.py", line 295, in <module>
    main(args, config)
  File "Grounding.py", line 187, in main
    state_dict = checkpoint['model']
KeyError: 'model'

**Comment by pqviet** [comment]
I made a mistake by set refcoco.pth in checkpoint.
I will close this issue.
