### ISSUE TITLE
NCCL problems of pretrain

### ISSUE THREAD

**Issue by Junjie-Ye** [salesforce/ALBEF#46]
I have a problem at pretrain phase, such as:
Traceback (most recent call last):
File "Pretrain.py", line 215, in
Traceback (most recent call last):
File "Pretrain.py", line 215, in
main(args, config)
File "Pretrain.py", line 93, in main
main(args, config)utils.init_distributed_mode(args)

File "Pretrain.py", line 93, in main
File "/root/albef/ALBEF/utils.py", line 257, in init_distributed_mode
utils.init_distributed_mode(args)
File "/root/albef/ALBEF/utils.py", line 257, in init_distributed_mode
torch.distributed.barrier()
File "/opt/conda/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 2420, in barrier
torch.distributed.barrier()
File "/opt/conda/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 2420, in barrier
work = default_pg.barrier(opts=opts)
RuntimeError: NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:825, unhandled system error, NCCL version 2.7.8
ncclSystemError: System call (socket, malloc, munmap, etc) failed.

Have you ever had a similar problem or give me some advice? Thanks!

**Comment by LiJunnan1992** [comment]
Were you able to run distributed training with any other Pytorch code before? You might want to check your cuda version.

**Comment by Junjie-Ye** [comment]
> Were you able to run distributed training with any other Pytorch code before? You might want to check your cuda version.

When I use torch 1.6.0, I won't face the problem. But the code needs to be worked with torch 1.8.0. Would you please give the environment.yml to me if it's convenient. Thanks a lot.

**Comment by yezi-yang** [comment]
Hi, I'm facing the same issue. How did you resolve it?
